	var picture2 = "\
MMMMMMMMMMMNNmmdhyshmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMmyyhhdhhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMNyhhhhhy+//+syymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMhhdyyyo/:---:/+odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMddy/::::::::::://hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMNho//::::/ooo+:.-/oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMds/+sso/:///:---:/MMMMMMMMMMMMMMMMMMMNmNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMh/////-.-://+//:+MMMMMMMMMMMMMMMMNhs+++o/:+yyNMMMMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMmo:-:/:/+o+++//-/hMMMMMMMMMMMMMNo/+//+///+oso+hdmMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMMo:/++/////////-``sMMMMMMMMMMMN/:ooss/..-:/+oso:oMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMMmy.://::::///-```-MMMMMMMMMMMMyosss/..------:+:oMMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMMMho--::/+//:```.:+NMMMMMMMMMMMdyhys/--:+oo:..---mMMMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMMNyhs:-----.`.-/yhy+dNMMMMMMMMMNyhhso//::/:.--:-:+/mMMMMMMMMMMMMMMMMMM\
\nMMMMMMMMMMNmyyys/-:://:-shddhyssshdmNMMMMMdhooss+-..-:///:::/NMNNMMMMMMMMMMMMMMM\
\nMMMMMMNmhhyhhsohhs+//++sdddhhyyyssyssydNMMNdydh+--//+/:::::-sdN/://odMMMMMMMMMMM\
\nMMMMmhyyyyhhy-:/shhsoyhddhhhhhhhhyyyyyyhdNMMMMMms:/+//:-:::--:o.`.-/sdMMMMMMMMMM\
\nMMMdhhhhhhhh/---:sddddddhhhhyyyhhhhhhhhhhhNMMmhy+.///////::-``     `-:/NMMMMMMMM\
\nMMmhddhhhhhh---::soo++///:/::/-+hhhhhhdhdhhNmo/..-:::::::--.``....--::-osMMMMMMM\
\nMMhhdddhhhhy.--:+s+syyyhyo-.+y/:hhhhddddddhyo-``.-........--.--.....````.sMMMMMM\
\nMmhdddddhhhs.--:y+.-shhhy.```oo.hhhdddddddh:..........```````.````````...-ymMMMM\
\nMhdddddddhh+--:+dh.`:soy/````:o`hdddddddddh+:-....`..``````````..````.-....:hMMM\
\ndhddddddddh+--:sddo`.s:+y````./.hddddddddddo:.```-:----::::..:://```.-.....-hMMM\
\nhhddddddddh/--:hddd:`/::o``````.yddddddhhyso+:.``:/-+//////--///:`..:--..-.-sMMM\
\nmyssyhhdddh:--/hdddy.:oss-``````:ddhyo+/::/+//-``:/.+//////:/+++/..-/-...-.:NMMM\
\nMh:--:/oy+h---/dddhh:-++:`````..`hdhs+:--:///:/.`//`+//////-s++++.--/:....--+sMM\
\nMd:--:/+s+y---/hddhh+````````:+y.sdhoo/:-://:/+:.//`/+++///-s++++---+/-...--:/yM\
\nNo--:/+os+o---:hddhhy```````-+oo-+dd/s/::-:/::/o--/`/++////++++o:---o/-..----ohM\
\nNo--:/+oo/+---/yddhhh/....--..---:ddyo+//--:/:/o:.::+++///+++o+:----o/-..----sMM\
\nM+..-:/ooss--:/sddhhhs.`.``:.:`//.ddd++//--:/:/o:`.:/++/++///:....--++:-....-hMM\
";